name: simple_easy_menssages
description: "Package Simple Easy Menssages"
version: 0.0.1
homepage: https://github.com/andersonmatte/simple_easy_menssages
repository: https://github.com/andersonmatte/simple_easy_menssages
issue_tracker: https://github.com/andersonmatte/simple_easy_menssages/issues
documentation: https://github.com/andersonmatte/simple_easy_menssages#readme
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  toastification: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.24.0

assets:
  - assets/Success.png
  - assets/Warning.png
  - assets/Error.png
  - assets/Custom.png
